<a href="https://colab.research.google.com/github/tab-h/xor_problem_nn/blob/main/XOR_problem_NN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim

In [4]:
"""
truth table:

input | out
______|_____
0  0  |  0
0  1  |  1
1  0  |  1
1  0  |  0

"""

'\ntruth table:\n\ninput | out\n______|_____\n0  0  |  0\n0  1  |  1\n1  0  |  1\n1  0  |  0\n\n'

In [12]:
# XOR inputs and outputs

inputs = torch.tensor([[0,0], [0,1], [1,0], [1,1]], dtype=torch.float32)
outputs = torch.tensor([[0], [1], [1], [0]], dtype=torch.float32)

In [13]:
class XORNet(nn.Module):

  def __init__(self):
    super(XORNet, self).__init__()
    self.hidden = nn.Linear(2, 2)  # Hidden layer with 2 neurons
    self.output = nn.Linear(2, 1)  # Output layer with 1 neuron
    self.activation = nn.Sigmoid()  # Sigmoid activation for binary output

  def forward(self, x):
    x = self.activation(self.hidden(x))  # Apply activation after hidden layer
    x = self.activation(self.output(x))  # Apply activation after output layer
    return x

In [43]:
model = XORNet()
criterion = nn.BCELoss()  # Binary Cross-Entropy Loss
optimizer = optim.Adam(model.parameters(), lr=0.01)  # Stochastic Gradient Descent

In [46]:
# train nn
epochs = 10000
for epoch in range(epochs):
    # forward pass
    preds = model(inputs)
    loss = criterion(preds, outputs)

    # backward pass
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # print loss every 1000 epochs
    if epoch % 1000 == 0:
        print("Epoch: ", epoch, " Loss: ", loss.item())

Epoch:  0  Loss:  8.218080620281398e-05
Epoch:  1000  Loss:  4.98512526974082e-05
Epoch:  2000  Loss:  3.0305043765110895e-05
Epoch:  3000  Loss:  1.8413045836496167e-05
Epoch:  4000  Loss:  1.1190245459147263e-05
Epoch:  5000  Loss:  6.813965228502639e-06
Epoch:  6000  Loss:  4.167397491983138e-06
Epoch:  7000  Loss:  2.5438687316636788e-06
Epoch:  8000  Loss:  1.5520540728175547e-06
Epoch:  9000  Loss:  9.369913414047915e-07


In [47]:
# test nn
with torch.no_grad():
    test_predictions = model(inputs)
    print("Predictions:")
    print(test_predictions)
    print("Rounded Predictions (binary):")
    print(torch.round(test_predictions))

Predictions:
tensor([[6.2389e-07],
        [1.0000e+00],
        [1.0000e+00],
        [6.0218e-07]])
Rounded Predictions (binary):
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [29]:
"""
tensor([[0.],
        [1.],
        [1.],
        [0.]])

corresponds to correct output values of truth table
"""